# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.1.1

pipelines:
  custom:
    phpcs: &sharedphpcs
    - step:
          name: Phpcs
          image: joomunited/phpcs
          script:
            - ln -s /root/.composer/vendor $BITBUCKET_CLONE_DIR/vendor
            - phpcs -s .
    codeception: &sharedcodeception
    - step:
        name: Codeception
        image: joomunited/codeception
        script:
        - wait_services.sh
        - $BITBUCKET_CLONE_DIR/tests/scripts/bitbucket_codeception.sh
        artifacts:
        - tests/_output/**
        services:
        - chromedriver
        - mysql
        - wordpress
  branches:
    '{master,development}': *sharedphpcs
    'development': *sharedcodeception

definitions:
  services:
    chromedriver:
      image: blueimp/chromedriver
    mysql:
      image: mysql:5.7.22
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    wordpress:
      image: joomunited/wordpress_cgi:latest